refactor(*): revise to support custom test functions (#130)
Update, for each exercise, its "runt*" and "test-*" scripts, to use optional custom test functions.

diff --git a/exercises/practice/resistor-color-duo/testlib/runt b/exercises/practice/resistor-color-duo/testlib/runt
--- a/exercises/practice/resistor-color-duo/testlib/runt
+++ b/exercises/practice/resistor-color-duo/testlib/runt
@@ -5,7 +5,8 @@
 #
 # $1 -> the test script (rexx)
 # $2 -> the application to test (rexx)
-# %3 -> optional shared variable definitions file (rexx)
+# $3 -> optional shared variable definitions file (rexx)
+# $4 -> optional custom testing functions definitions file (rexx)
 #
 # This script concatenates the files:
 #
@@ -14,6 +15,10 @@
 # or, if optional file specified:
 #
 #   ${3}.rexx + t1.rexx + ${1}.rexx + t2.rexx + ${2}.rexx + t3.rexx
+#
+# or, if both optional files specified:
+#
+#   ${3}.rexx + t1.rexx + ${1}.rexx + t2.rexx + ${2}.rexx + ${4}.rexx + t3.rexx
 #
 # and executes the resulting test runner file. The return code from the
 # test runner is passed back to the command-line. Valid return code values:
@@ -40,6 +45,7 @@
 # 2023-04-14      0.6.0     Anthony J. Borla    Added JSON option.
 # 2023-04-15      0.7.0     Anthony J. Borla    Added toplevel support.
 # 2023-04-15      0.7.1     Anthony J. Borla    Revise header commentary.
+# 2024-07-27      0.7.2     Anthony J. Borla    Support test functions.
 # -----------------------------------------------------------------------------
 
 # ---- Constants
@@ -50,13 +56,14 @@ INTERPRETER="rexx"
 # ---- Functions
 
 usage() {
-    echo "Usage: ${0} [-h | --help] | [--keep] [--tap|--json] [--regina] test source [toplevel]"
+    echo "Usage: ${0} [-h | --help] | [--keep] [--tap|--json] [--regina] test source [toplevel] [checkfuncs]"
 }
 
 help() {
     echo 'Executes t-rexx unit test runner using supplied Rexx test script on specified Rexx source file.'
     echo ' * ${1} is the test script name, ${2} is the source file (code under test), both sans .rexx extension'
     echo ' * ${3} is an optional Rexx file containing variables shared by the code under test (sans .rexx extension)'
+    echo ' * ${4} is another optional Rexx file containing custom functions used in testing'
     echo ' * --tap option generates TAP-compliant output; default is verbose report style'
     echo ' * --json option packages report style output as a JSON array (incompatible with --tap option)'
     echo ' * --keep option ensures the generated test runner is not deleted'
@@ -93,17 +100,20 @@ done
 [ -n "${TAP}" -a -n "${JSON}" ] && error 'Incorrect option combination: either --tap or --json, not both'
 
 # Expecting two, or three, positional parameters; bail if not supplied
-[ "$#" -ne "2" -a "$#" -ne "3" ] && error 'Incorrect arguments'
+[ "$#" -ne "2" -a "$#" -ne "3" -a "$#" -ne "4" ] && error 'Incorrect arguments'
 
 # Expecting each positional parameter to be a Rexx filename
 [ -f "${1}.rexx" ] || error "Missing test script - ${1}.rexx"
 [ -f "${2}.rexx" ] || error "Missing source file - ${2}.rexx"
+[ "$#" -eq "4" ] && { [ -f "${4}.rexx" ] || error "Missing checkfuncs file - ${4}.rexx" ; }
 [ "$#" -eq "3" ] && { [ -f "${3}.rexx" ] || error "Missing toplevel file - ${3}.rexx" ; }
 
 # Assemble test runner from components and supplied files
-[ "$#" -eq "3" ] \
-    && cat "${3}.rexx" t1.rexx "${1}.rexx" t2.rexx "${2}.rexx" t3.rexx > "${RUNNER}" 2>/dev/null \
-    || cat t1.rexx "${1}.rexx" t2.rexx "${2}.rexx" t3.rexx > "${RUNNER}" 2>/dev/null
+case "$#" in
+    4) cat "${3}.rexx" t1.rexx "${1}.rexx" t2.rexx "${2}.rexx" "${4}.rexx" t3.rexx > "${RUNNER}" 2>/dev/null ;;
+    3) cat "${3}.rexx" t1.rexx "${1}.rexx" t2.rexx "${2}.rexx" t3.rexx > "${RUNNER}" 2>/dev/null ;;
+    *) cat t1.rexx "${1}.rexx" t2.rexx "${2}.rexx" t3.rexx > "${RUNNER}" 2>/dev/null ;;
+esac
 
 # Set output option
 [ -n "${TAP}" ] && OUT="${TAP}"
